// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtYR1sYig17JzsWWcv_9v7zuVAvsJXFYU',
    appId: '1:993737959089:web:da94300ffaf8b88d7c2490',
    messagingSenderId: '993737959089',
    projectId: 'copa2022-480e0',
    authDomain: 'copa2022-480e0.firebaseapp.com',
    storageBucket: 'copa2022-480e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP3aA88NtVyko7aSzTqcfqQ3_x1O2_3tA',
    appId: '1:993737959089:android:4e60309a1f82797b7c2490',
    messagingSenderId: '993737959089',
    projectId: 'copa2022-480e0',
    storageBucket: 'copa2022-480e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_32llXvhp7wcYC4neYkaC8mFRHY14E7U',
    appId: '1:993737959089:ios:461f236433271c077c2490',
    messagingSenderId: '993737959089',
    projectId: 'copa2022-480e0',
    storageBucket: 'copa2022-480e0.appspot.com',
    iosClientId: '993737959089-pc0lp2ief5kpn93ids7jumb6bm4j1elp.apps.googleusercontent.com',
    iosBundleId: 'br.com.sharlon.copaDoMundo2022',
  );
}
